Gopkg.lock, examples/create-secure-policy/main.tf, sysdig/provider.go, sysdig/resource_sysdig_secure_notification_channel.go, sysdig/resource_sysdig_secure_policy.go, sysdig/sysdig_secure_client.go, sysdig/sysdig_secure_models.go
This Pull Request adds the Notification Channel resource and some examples.
In this changes, there's support for the following channel types: 
It also adds references from the Policies to the Notification Channels
=> Add Notification Channel resource and its handling

.gitignore, scripts/oanc/main.go, sysdig/resource_sysdig_secure_notification_channel.go, sysdig/secure/models.go
Adds PagerDuty as a valid notification channel for the `sysdig_secure_notification_channel` resource, and adds support for generating a valid PagerDuty resource block in the `oanc` script.
=> Support PagerDuty as a Notification Channel

examples/team.tf, sysdig/provider.go, sysdig/resource_sysdig_secure_team.go, sysdig/resource_sysdig_secure_team_test.go, sysdig/secure/client.go, sysdig/secure/models.go, sysdig/secure/teams.go
- Add `sysdig_secure_team` resource
- This PR is related to #11 
- I think we have additional discussion topic about this PR.
- So I'll write comment on the point which I want reviewers to check.
<details><summary>make testacc</summary><div>
```bash
$ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v  -timeout 120m
?   	github.com/draios/terraform-provider-sysdig	[no test files]
?   	github.com/draios/terraform-provider-sysdig/scripts/oanc	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccAlertAnomaly
=== PAUSE TestAccAlertAnomaly
=== RUN   TestAccAlertDowntime
=== PAUSE TestAccAlertDowntime
=== RUN   TestAccAlertEvent
=== PAUSE TestAccAlertEvent
=== RUN   TestAccAlertGroupOutlier
=== PAUSE …
```
=> Add team resource for Sysdig Secure

sysdig/common/client.go, sysdig/monitor/client.go, sysdig/provider.go, sysdig/secure/client.go, sysdig/sysdig_clients.go
This PR adds an `extra_headers` field to the provider's configuration that would allow users of the provider to authenticate with custom methods. 
The headers can overwrite the existing `Authorization` and `Content-Type`.
=> feat: Add custom headers option to the provider and the client

sysdig/secure/client.go
Default Transport in http package supports proxy from standard env variables, see line 37 on:
https://golang.org/src/net/http/transport.go
Using a custom Transport overrides this setting, which is standard and should be supported.
=> Support proxy from env vars

website/docs/r/sysdig_monitor_dashboard.md, website/sysdig.erb
This PR adds documentation for the `sysdig_monitor_dashboard` resource.
=> docs: Add documentation for sysdig_monitor_dashboard

docs/index.md
This PR updates the main page explaining the Terraform provider at https://sysdiglabs.github.io/terraform-provider-sysdig/
=> docs: Update documentation with new resources

.github/workflows/codeql-analysis.yml
This PR adds a GitHub Code Scan workflow to Git Hub actions for the repository, to look for vulnerabilities in the code and libraries used, with the following characteristics:
* It will scan the repository for vulnerabilities periodically (in case the vulnerability db updates with new ones), each Friday at 6:00 AM.
* It will trigger on push or pull requests to master
* It will scan go language files (autodetected supported programming language)
* It is non blocking, meaning that a detection will not block the pipeline
* Security alerts can be checked at: https://github.com/sysdiglabs/terraform-provider-sysdig/security/code-scanning
=> ci: Added GH Code Scan action

sysdig/resource_sysdig_secure_rule.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, sysdig/secure/models.go, website/docs/r/sysdig_secure_rule_container.md, website/docs/r/sysdig_secure_rule_falco.md, website/docs/r/sysdig_secure_rule_filesystem.md, website/docs/r/sysdig_secure_rule_network.md, website/docs/r/sysdig_secure_rule_process.md, website/docs/r/sysdig_secure_rule_syscall.md
The current scenario is that even for `append=true` Falco rules, almost all the fields are still required, like description, output and priority.
This PR allows having only name, condition and append=true set for a new rule appending to an existing one.
=> feat: Allow minimal configuration while appending to Falco rule

sysdig/resource_sysdig_secure_list.go, sysdig/resource_sysdig_secure_macro.go, sysdig/resource_sysdig_secure_rule_container.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_process.go, sysdig/resource_sysdig_secure_rule_syscall.go
Customers like Yahoo Japan are encountering "context deadline exceeded" errors while using the provider. For them, working with some sysdig resources may take longer than 30 seconds. This PR increases the timeout for those resources.
=> feat: Increase timeout for lists, macros and rules

sysdig/resource_sysdig_monitor_alert_common.go, sysdig/resource_sysdig_monitor_team.go, sysdig/resource_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_rule_network.go, sysdig/resource_sysdig_secure_rule_process_test.go
Some fields weren't being correctly set when retrieved from the API, like:
- `severity` in all `sysdig_monitor_alert_*` resources
- `can_see_infrastructure_events` in `sysdig_monitor_team`
- `can_use_aws_data` in `sysdig_monitor_team`
- `severity` in `sysdig_secure_policy`
Also
- `tcp.ports` and `udp.ports` in `sysdig_secure_rule_network` weren't being created correctly in the backend, thus, creating a network rule with no checked ports.
=> fix: Solve fields not correctly set in multiple resources

sysdig/monitor/models.go, sysdig/resource_sysdig_monitor_alert_anomaly_test.go, sysdig/resource_sysdig_monitor_alert_common.go, website/docs/r/sysdig_monitor_alert_anomaly.md, website/docs/r/sysdig_monitor_alert_downtime.md, website/docs/r/sysdig_monitor_alert_event.md, website/docs/r/sysdig_monitor_alert_group_outlier.md, website/docs/r/sysdig_monitor_alert_metric.md
This PR the possibility to define a custom notification where the title can be modified and some text can be prepended or appended to the alert body.
Closes #40.
=> feat: Add custom notification config for Monitor alerts

sysdig/resource_sysdig_monitor_alert_event.go
The previous regexp wasn't able to catch up quantifier with multiple chars like `>=` `<=` `!=`
This change fix also the possibility to discard multiple whitespaces between groups (https://regex101.com/r/79VIkC/1)
=> Fix regexp in order to match right strings and multiple whitespaces

.github/workflows/stale.yml
The stale action requires v3 for the given parameters. This PR updates it.
=> ci: Update stale action to v3

go.sum, sysdig/internal/client/secure/models.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, website/docs/r/sysdig_secure_rule_falco.md
Adds support for [Falco exceptions](https://falco.org/docs/rules/exceptions/) in `sysdig_secure_rule_falco` resources.
Closes #106.
=> feat: Add support for Falco exceptions

sysdig/data_source_sysdig_secure_trusted_cloud_identity.go, sysdig/resource_sysdig_secure_cloud_account.go
Add validation to the `cloud_provider` param of the `sysdig_secure_trusted_cloud_identity` datasource as suggested here: https://github.com/sysdiglabs/terraform-provider-sysdig/pull/113#discussion_r690289600
Also adds this same validation to the `sysdig_secure_cloud_account` resource.
This PR does not need to be released immediately, it can go along with the next functional release.
=> Add validation to cloud_provider

sysdig/internal/client/secure/cloud_account.go
The trustedIdentity datasource was not properly unmarshalling the string response from the backend, resulting in extra quotations that broke the consumer. 
Add a fix to properly unmarshal this response.
=> Properly unmarshal trustedIdentity response

sysdig/internal/client/secure/benchmark_task.go, sysdig/internal/client/secure/client.go, sysdig/internal/client/secure/models.go, sysdig/provider.go, sysdig/resource_sysdig_secure_benchmark_task.go, sysdig/resource_sysdig_secure_benchmark_task_test.go, website/docs/r/sysdig_secure_benchmark_task.md, website/docs/r/sysdig_secure_cloud_account.md, website/sysdig.erb
We would like to add the ability to https://github.com/sysdiglabs/terraform-aws-secure-for-cloud to automatically create a benchmark task when using the cloud-bench module. 
This PR adds a Secure Benchmark Task resource.
Tested using a local build and https://github.com/sysdiglabs/terraform-aws-secure-for-cloud/pull/17
=> Add Benchmark Task resource

sysdig/provider.go, sysdig/resource_sysdig_monitor_alert_promql.go, sysdig/resource_sysdig_monitor_alert_promql_test.go, website/docs/r/sysdig_monitor_alert_promql.md, website/sysdig.erb
This adds support to PromQL alerts using the new resource: `sysdig_monitor_alert_promql`.
The same could be achieved in a more succinct way defining a new field in the resource `sysdig_monitor_alert_metric` as described by the good PR https://github.com/sysdiglabs/terraform-provider-sysdig/pull/123, reported here is an alternative way: my understanding is that a new resource could provide a more coherent interface from a user perspective.
=> feat: Support for PromQL Alerts (#108)

sysdig/data_source_sysdig_secure_trusted_cloud_identity.go, sysdig/helpers.go, website/docs/d/secure_trusted_cloud_identity.md
What was previously referred to as the client ID is actually the service principal ID; client ID should represent the ID of the application in which the service principal lives, and is not needed by the TF provider.
=> Refactor Azure Service Principal Attributes

sysdig/internal/client/common/client.go
Currently, API calls for "Sysdig Platform" resources/data sources from the "common" client don't respect proxy env vars (HTTPS_PROXY, NO_PROXY, etc.). When using the provider behind a proxy, this results in what seems like a provider hang.
While the monitor & secure clients do work behind a proxy & respect proxy env vars, any management of platform resources (ie. `resource "sysdig_user"`, `data "sysdig_current_user"`) fails behind a proxy.
This PR configures the common client to respect proxy settings like the [monitor](https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/internal/client/monitor/client.go#L50) & [secure](https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/internal/client/secure/client.go#L79) clients already do.
=> Respect proxy env vars in common HTTP client

sysdig/internal/client/secure/cloud_account.go
URL needs to include `upsert` query param to upsert a cloud account if it already exists, avoiding 409 conflict
=> Update cloud account URL to upsert

sysdig/data_source_sysdig_fargate_workload_agent.go
Starting from v2.2.0, the expected entry point is `logwriter`.
=> fix: update entry_point for workload-agent > 2.2.0

sysdig/internal/client/secure/client.go
Clone from the http.DefaultTransport to use sane defaults instead of zeroed values from a new http.Transport{} struct.
=> Clone from default HTTP transport to prevent issues with zeroed values

website/docs/d/fargate_workload_agent.md
The `sysdig_fargate_workload_agent` is supposed to have containers, not
task definitions.
=> doc: use a more specific name on `sysdig_fargate_workload_agent` example

sysdig/internal/client/monitor/helpers.go
The API doesn't return the error in the same format as the provider expected.
> panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation
=> fix: Solve API not returning the expected error format

sysdig/resource_sysdig_secure_benchmark_task.go, sysdig/resource_sysdig_secure_cloud_account.go
Other TF providers create a resource if it is missing (i.e. was manually deleted) instead of throwing a 404
Jira ticket: https://sysdig.atlassian.net/browse/SSPROD-12557
=> Support auto creation of missing benchmark resources (SSPROD-12557)

sysdig/data_source_sysdig_fargate_ECS_test.go, sysdig/data_source_sysdig_fargate_workload_agent.go, sysdig/testfiles/fargate_log_group.json, sysdig/testfiles/fargate_log_group_expected.json, website/docs/d/fargate_workload_agent.md
Adds a new optional parameter block `log_configuration` which can be used to configure the `LogConfiguration` block on the sysdig instrumentation container, using the `awslogs` driver.
=> feat: configure Fargate instrumentation log group

.github/workflows/ci-pull-request.yml, go.mod, sysdig/data_source_sysdig_fargate_ECS_test.go, sysdig/data_source_sysdig_fargate_workload_agent.go, sysdig/data_source_sysdig_fargate_workload_agent_test.go, sysdig/testfiles/ECSInstrumented.json, sysdig/testfiles/fargate_cmd_test_expected.json, sysdig/testfiles/fargate_combined_test_expected.json, sysdig/testfiles/fargate_entrypoint_test_expected.json, sysdig/testfiles/fargate_env_test_expected.json, sysdig/testfiles/fargate_linuxparameters_test_expected.json, sysdig/testfiles/fargate_log_group_expected.json, sysdig/testfiles/fargate_volumesfrom_test_expected.json, website/docs/d/fargate_workload_agent.md
This PR adds the parameter `sysdig_logging` to the `fargate_workload_agent` so that users can set the instrumentation logging level at deployment time.
=> fix: add the parameter sysdig_logging to the fargate_workload_agent

GNUmakefile, README.md
Add `make install` to copy the provider to be used locally.
=> feat: Add a target to install/uninstall the provider locally

website/docs/d/fargate_workload_agent.md
There's no benefit in running direct mode, so remove the documentation for it. The right way of connecting to the backend is via the orchestrator agent.
=> doc: remove documentation about direct mode

website/docs/index.md
- add links to docs for both saas region url and api key value retrieval
=> docs: clarify provider authentication options

sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, website/docs/r/secure_rule_falco.md
The comps field can be optional in the API, and is automatically evaluated with a default value when imported in Falco and Cloud Connector.
=> feat: Make comps optional for falco exceptions

sysdig/resource_sysdig_monitor_alert_anomaly.go, sysdig/resource_sysdig_monitor_alert_group_outlier.go, website/docs/r/monitor_alert_anomaly.md, website/docs/r/monitor_alert_group_outlier.md
Deprecate `sysdig_monitor_alert_anomaly` and `sysdig_monitor_alert_group_outlier` resources.
=> feat(monitor): deprecate not supported resources

README.md, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, website/docs/r/secure_rule_falco.md
This PR fixes the way falco rule exceptions are handled.
=> fix(secure-policy): Update falco rule exceptions type to match falco expectations

CODEOWNERS, sysdig/internal/client/secure/cloud_account.go, sysdig/internal/client/secure/models.go, sysdig/resource_sysdig_secure_cloud_account.go, sysdig/resource_sysdig_secure_cloud_account_test.go, website/docs/r/secure_cloud_account.md
- Adding a new field in sysdig cloud account. its called `workload_identity_account_id`
- This is only used for GCP
- If a customer has GCP Org set up, then this field needs to be set to `account id` in which workload identity for current 
account is set up.
=> feat(cloud-account): add new workload identity field for gcp organizational

sysdig/internal/client/secure/models.go, sysdig/resource_sysdig_secure_rule_falco.go, website/docs/r/secure_rule_falco.md
This PR adds support for exceptions that use just name and value.
=> fix(secure-policy): Add support for name/value exceptions

sysdig/internal/client/secure/models.go, sysdig/resource_sysdig_secure_rule_falco.go, website/docs/r/secure_rule_falco.md
This PR adjusts the support for exceptions so that fields and comps are optional.  It also fixes the issue of adding a property that is not used by falco.
=> fix(secure-policy) Fix falco rule support to allow fields and comps to be optional

README.md
clarify acceptance test env on readme
=> docs: clarify acceptance test env

.github/workflows/ci-scheduled-tests.yml
Actually, when the scheduled test fails, the slack notification doesn't work properly.
Following Github actions documentation (https://docs.github.com/en/actions/learn-github-actions/expressions#failure), we update the condition to detect any failure in the previous job (test).
=> ci(Github): fix notification failure condition

sysdig/internal/client/secure/client.go, sysdig/internal/client/secure/models.go, sysdig/internal/client/secure/scanningpolicies.go, sysdig/provider.go, sysdig/resource_sysdig_secure_scanningpolicies.go, sysdig/resource_sysdig_secure_scanningpolicies_test.go, sysdig/resource_sysdig_secure_scanningpoliciesassignments.go, sysdig/resource_sysdig_secure_scanningpoliciesassignments_test.go, website/docs/r/secure_scanning_policy.md, website/docs/r/secure_scanning_policy_assignment.md
This PR adds support for scanning policy and scanning policy assignments for Legacy Engine.
Note: As scanning policy assignments (/mappings) only support GET/PUT, the destroy action returns the mapping to the default configuration (*/*:* assigned to Default policy)
=> feat(legacy scanning policies and assignments): Add scanning policies and assignments for legacy engine

sysdig/resource_sysdig_monitor_dashboard.go, sysdig/resource_sysdig_monitor_dashboard_test.go, website/docs/r/monitor_dashboard.md
This PR adds support for legend configuration inside time chart panel. To stay backward compatible, if legend is not provided, default one will be used.
=> feat(dashboard) Expose legend configuration on panel

sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, website/docs/r/secure_rule_falco.md
**It's a copied PR from https://github.com/sysdiglabs/terraform-provider-sysdig/pull/257 to solve test failed.**
I've added GCP and Azure data sources to the validation.
**Scope**
It affects `sysdig_secure_rule_falco` resource.
**Runbook**
with the current master  branch, when adding GCP rule,
```
resource "sysdig_secure_rule_falco" "gcp_example" {
name = "Database Snapshot snake"
source = "gcp_auditlog"
condition = "gcp.serviceName = 'compute.googleapis.com"
output = "%gcp.serviceName"
}
```
This terraform provider returns the below validation error
```
Error: expected [{pathStepImpl:{} Name:source}] to be one of [syscall k8s_audit aws_cloudtrail], got gcp_auditlog
with sysdig_secure_rule_falco.gcp_example,
on main.tf line 93, in resource "sysdig_secure_rule_falco" "gcp_example":
93: …
```
=> GCP and Azure Falco rule support

sysdig/resource_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_policy_test.go
This fixes the issue when actions DTO schema from API is applied on terraform state schema (which is different).
=> fix(policy): fix actions to not apply different schema on actions in state

.gitignore, GNUmakefile
Remove tee comand from output as it was overrinding the final result
=> fix: Remove tee comand from output as it was overrinding the final result

.github/workflows/test.yml, sysdig/internal/client/v2/client.go, sysdig/internal/client/v2/config.go, sysdig/internal/client/v2/ibm.go, sysdig/internal/client/v2/ibm_test.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_monitor_team.go, sysdig/resource_sysdig_monitor_team_ibm_test.go, sysdig/sysdig_clients.go, website/docs/index.md, website/docs/r/monitor_team.md
Added features:
- We are adding support for IBM Auth on IBM Cloud Monitoring. Provider is extended with IBM specific arguments (and doc is updated).
- Two new options are added  on monitor team resource (and doc is updated):
- `enable_ibm_platform_metrics` - enables platform metrics on IBM Cloud Monitoring
- `ibm_platform_metrics` - defines platform metrics on IBM Cloud Monitoring
- `ibm_monitor_team_id` provider argument is removed. We do not want to support it yet.
=> feat(teams): add ibm platform metrics in teams

GNUmakefile, sysdig/data_source_sysdig_secure_current_connection_test.go
=> fix[tests]: Fix secure connection tests when run against secure-staging instead of prod

sysdig/resource_sysdig_secure_rule.go
If the tags are all the same, but happen to be in a different order, we should not consider that a change to the rule.
=> tag order should not matter when comparing rules

sysdig/resource_sysdig_secure_policy.go
When the actions block in a module is empty, this can result in a condition in which terraform is identifying the resource as having changed.  This PR changes this so it identifies the default state.
=> Default state in a policy actions block should not result in unexpected state change in terraform

CODEOWNERS
Adding more members of the detection backend team as code owners for policies/rules
=> add detection backend team members to codeowners

GNUmakefile
Fix the order of QA test execution order. It was causing some failures in the executions to be markes as passed when it was not true.
=> tests: Fix test execution param order

sysdig/common_test.go, sysdig/internal/client/v2/client.go, sysdig/internal/client/v2/ibm.go, sysdig/internal/client/v2/ibm_test.go, sysdig/internal/client/v2/sysdig.go, sysdig/internal/client/v2/sysdig_test.go
=> fix(client): revert sysdig provider header back

sysdig/data_source_sysdig_secure_managed_policy.go, sysdig/data_source_sysdig_secure_managed_policy_test.go, sysdig/data_source_sysdig_secure_policy.go, sysdig/provider.go, website/docs/d/secure_managed_policy.md, website/docs/r/secure_managed_policy.md, website/docs/r/secure_policy.md
This PR adds a new data source `sysdig_secure_managed_policy` that can be used for getting data from managed policies.
=> feat(policies): Data Source for managed policies

sysdig/data_source_sysdig_secure_rule.go, sysdig/data_source_sysdig_secure_rule_container.go, sysdig/data_source_sysdig_secure_rule_container_test.go, sysdig/internal/client/v2/model.go, sysdig/internal/client/v2/rules.go, sysdig/provider.go, sysdig/resource_sysdig_secure_rule_container.go, website/docs/d/secure_managed_policy.md, website/docs/d/secure_managed_ruleset.md, website/docs/d/secure_notification_channel.md, website/docs/d/secure_rule_container.md
This PR adds a new data source for `sysdig_secure_rule_container` that can be used for getting data from "container" rules.
=> feat(policies): data source for "container" rules

sysdig/provider.go, sysdig/resource_sysdig_secure_custom_policy.go, sysdig/resource_sysdig_secure_custom_policy_test.go, sysdig/resource_sysdig_secure_policy.go, website/docs/r/secure_custom_policy.md, website/docs/r/secure_policy.md
This PR adds a new resource for `sysdig_secure_custom_policy` and adds a deprecation notice to `sysdig_secure_policy`.  `sysdig_secure_policy` will still work, but usage should be replaced with one of the more specific policy types:
* `sysdig_secure_custom_policy`
* `sysdig_secure_managed_policy`
* `sysdig_secure_managed_ruleset`
=> feat(policies): resource for custom policies

sysdig/data_source_sysdig_secure_custom_policy.go, sysdig/data_source_sysdig_secure_custom_policy_test.go, sysdig/data_source_sysdig_secure_managed_policy.go, sysdig/data_source_sysdig_secure_policy.go, sysdig/provider.go, website/docs/d/secure_custom_policy.md
This PR adds a new data source for sysdig_secure_custom_policy.
=> feat(policies): data source for custom policies

sysdig/data_source_sysdig_secure_rule_filesystem.go, sysdig/data_source_sysdig_secure_rule_filesystem_test.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_secure_rule_filesystem.go, website/docs/d/secure_rule_filesystem.md
This PR ensures that the data source and resource are consistent in their naming.
=> fix(policies): update for consistency between resource and data source

sysdig/data_source_sysdig_secure_rule_falco.go, sysdig/data_source_sysdig_secure_rule_falco_count.go, sysdig/data_source_sysdig_secure_rule_falco_count_test.go, sysdig/data_source_sysdig_secure_rule_falco_test.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_secure_rule_falco.go, website/docs/d/secure_rule_falco.md, website/docs/d/secure_rule_falco_count.md
This PR adds new data sources for sysdig_secure_rule_falco and sysdig_secure_rule_falco_count.
=> feat(policies): data source falco rules

sysdig/data_source_sysdig_secure_rule.go, sysdig/data_source_sysdig_secure_rule_container.go, sysdig/data_source_sysdig_secure_rule_network.go, sysdig/data_source_sysdig_secure_rule_network_test.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_secure_rule_network.go, website/docs/d/secure_rule_network.md
This PR adds a new data source for sysdig_secure_rule_network.
=> feat(policies): Data source for sysdig_secure_rule_network

sysdig/data_source_sysdig_secure_notification_channel_test.go, sysdig/resource_sysdig_monitor_notification_channel_email_test.go, sysdig/resource_sysdig_monitor_notification_channel_opsgenie_test.go, sysdig/resource_sysdig_monitor_notification_channel_pagerduty_test.go, sysdig/resource_sysdig_monitor_notification_channel_slack_test.go, sysdig/resource_sysdig_monitor_notification_channel_sns_test.go, sysdig/resource_sysdig_monitor_notification_channel_victorops_test.go, sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go, sysdig/resource_sysdig_monitor_team_shared_test.go, sysdig/resource_sysdig_monitor_team_test.go, sysdig/resource_sysdig_secure_cloud_account_test.go, sysdig/resource_sysdig_secure_notification_channel_email_test.go, sysdig/resource_sysdig_secure_notification_channel_opsgenie_test.go, sysdig/resource_sysdig_secure_notification_channel_pagerduty_test.go, sysdig/resource_sysdig_secure_notification_channel_slack_test.go, sysdig/resource_sysdig_secure_notification_channel_sns_test.go, sysdig/resource_sysdig_secure_notification_channel_victorops_test.go, sysdig/resource_sysdig_secure_notification_channel_webhook_test.go, sysdig/resource_sysdig_secure_team_test.go
Added `tf_acc_sysdig_common` tag which will be used to run resources which are common for both monitor and secure.
=> feat(test): add common test tag

sysdig/data_source_sysdig_secure_rule_falco.go, sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_secure_macro.go, sysdig/resource_sysdig_secure_macro_test.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, website/docs/d/secure_rule_falco.md, website/docs/r/secure_macro.md, website/docs/r/secure_rule_falco.md
This PR:
* adds the `minimum_engine_version` argument to the falco_rule and macro resource
* adds the `minimum_engine_version` attribute to the falco_rule data source.
=> feat(policies): add `minimum_engine_version` argument to macro and falco rule resources

GNUmakefile, sysdig/resource_sysdig_monitor_team.go, sysdig/resource_sysdig_secure_team.go
This PR includes:
- allow teams on IBM to create platform metrics regardless of auth method used
- add debug logs for command used by Jenkins
=> feat(teams): allow ibm metrics on sysdig token

website/docs/index.md
- This PR affects the provider index documentation updating the URLs we have in the examples for IBM Cloud (IBM Cloud Monitoring and Workload Protection) to use production URL examples.
- We have also added the links to IBM Cloud documentation to get the region URL
=> Updated IBM authentication examples to use prod URLs

sysdig/common.go, sysdig/internal/client/v2/model.go, sysdig/internal/client/v2/sysdig.go, sysdig/internal/client/v2/team_service_account.go, sysdig/provider.go, sysdig/resource_sysdig_team_service_account.go, sysdig/resource_sysdig_team_service_account_test.go, website/docs/r/team_service_account.md
This PR adds support for managing team service account via `sysdig_team_service_account` resource for both monitor and secure teams.
=> feat (team service account)  Manage Team Based Service Account as Terraform resource

sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_monitor_alert_v2_prometheus.go, sysdig/resource_sysdig_monitor_alert_v2_prometheus_test.go, website/docs/r/monitor_alert_v2_prometheus.md
Add new `keep_firing_for_minutes` field to `sysdig_monitor_alert_v2_prometheus` resource, implementing the feature "Alert Resolution Delay" described in https://docs.sysdig.com/en/docs/sysdig-monitor/alerts/alert-types/promql-alerts/#define-a-promql-alert
=> feat(alerts): add keep_firing_for_minutes field

sysdig/data_source_sysdig_custom_role.go, sysdig/data_source_sysdig_custom_role_test.go, sysdig/provider.go, sysdig/resource_sysdig_monitor_team.go, sysdig/resource_sysdig_secure_team.go, website/docs/d/custom_role.md, website/docs/r/monitor_team.md, website/docs/r/secure_team.md
Add the ability to assign custom roles to users in teams
Changes made in the PR:
- Add custom role data source
- Add documentation
- Removed validation on role because thats already done on BE
- Updated team documentation to show how to assign custom role to a user
=> feat(teams) Add the ability to assign CustomRoles to users in teams

sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_secure_posture_zone.go
Exclude username from `PostureZoneRequest` since it's now automatically added in the backend.
=> fix(posture_zone): exclude username from zone request

sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_monitor_notification_channel_webhook.go, sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go, sysdig/resource_sysdig_secure_notification_channel_webhook.go, sysdig/resource_sysdig_secure_notification_channel_webhook_test.go, website/docs/r/monitor_notification_channel_webhook.md, website/docs/r/secure_notification_channel_webhook.md
add new fields to webhook notification channels:
* `allow_insecure_connections`
* `custom_data`
=> feat(notification channel): add fields to webhook notification channels

sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_monitor_notification_channel_slack.go, sysdig/resource_sysdig_monitor_notification_channel_slack_test.go, website/docs/r/monitor_notification_channel_slack.md
add arguments to `sysdig_monitor_notification_channel_slack` resource to control slack messages format.
=> feat(notification channel): add new arguments to monitor slack notification channels

sysdig/resource_sysdig_monitor_notification_channel_team_email_test.go, sysdig/resource_sysdig_secure_notification_channel_team_email_test.go
make team name random in tests to that previous dangling resources does not block next tests.
=> fix(tests): remove fixed team name in tests

sysdig/internal/client/v2/client.go, sysdig/internal/client/v2/model.go, sysdig/internal/client/v2/silence_rule.go, sysdig/provider.go, sysdig/resource_sysdig_monitor_silence_rule.go, sysdig/resource_sysdig_monitor_silence_rule_test.go, website/docs/index.md, website/docs/r/monitor_silence_rule.md
Implement new resource `sysdig_monitor_silence_rule` to support [Silence Alert Notifications
](https://docs.sysdig.com/en/docs/sysdig-monitor/alerts/silence-alert-notifications) feature in the terraform provider.
=> feat(monitor): resource for silence rule

sysdig/internal/client/v2/alerts_v2.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_monitor_alert_v2_change_test.go, sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus.go, sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus_test.go, sysdig/resource_sysdig_monitor_alert_v2_metric_test.go, website/docs/index.md, website/docs/r/monitor_alert_v2_event.md, website/docs/r/monitor_alert_v2_form_based_prometheus.md, website/docs/r/monitor_alert_v2_metric.md, website/docs/r/monitor_alert_v2_prometheus.md
add new alert type: `sysdig_monitor_alert_v2_form_based_prometheus`, implementing the feature described in https://docs.sysdig.com/en/docs/sysdig-monitor/alerts/alert-types/metric-alerts/#translate-to-promql.
=> feat(alerts): add form based prometheus alert type 

sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus_test.go
scope down query in tests for `sysdig_monitor_alert_v2_form_based_prometheus` so that we can test also in segment restricted environments.
=> fix(tests): scope down query in tests

sysdig/internal/client/v2/rules.go, sysdig/resource_sysdig_secure_custom_policy.go, sysdig/resource_sysdig_secure_managed_policy.go, sysdig/resource_sysdig_secure_managed_ruleset.go, sysdig/resource_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_rule_container.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_filesystem.go, sysdig/resource_sysdig_secure_rule_network.go, sysdig/resource_sysdig_secure_rule_process.go, sysdig/resource_sysdig_secure_rule_syscall.go
We should differentiate between 404 errors and all other errors when trying to get a rule from the backend. If the response is non 404, we should not try to re-create the resource, as it might already exist.
=> feat(secure-rule, secure-policy) use status code to determine if resource needs to be recreated

sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_monitor_alert_v2_change.go, sysdig/resource_sysdig_monitor_alert_v2_change_test.go, sysdig/resource_sysdig_monitor_alert_v2_downtime.go, sysdig/resource_sysdig_monitor_alert_v2_downtime_test.go, sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus.go, sysdig/resource_sysdig_monitor_alert_v2_metric.go, sysdig/resource_sysdig_monitor_alert_v2_metric_test.go, website/docs/r/monitor_alert_v2_change.md, website/docs/r/monitor_alert_v2_downtime.md, website/docs/r/monitor_alert_v2_form_based_prometheus.md, website/docs/r/monitor_alert_v2_metric.md
add `unreported_alert_notifications_retention_seconds` argument to alerts of type `monitor_alert_v2_metric`, `monitor_alert_v2_change`, `monitor_alert_v2_downtime`, `sysdig_monitor_alert_v2_form_based_prometheus`.
=> feat(alerts): add unreported_alert_notifications_retention_seconds argument to alerts

CODEOWNERS
Add platform team as codeowner for internal code.
=> feat(codeowners): add codeowners for internal components

sysdig/common.go, sysdig/resource_sysdig_secure_cloud_auth_account.go
Current (and working) TF snippet expected from `onboarding-api` :-
```
terraform {
required_providers {
sysdig = {
source = "local/sysdiglabs/sysdig"
version = "~> 1.0.0"
}
}
}
provider "sysdig" {
sysdig_secure_url          = "https://secure-staging.sysdig.com"
sysdig_secure_api_token    = "fgb6xxxx-xxxxx-xxxxx-xxxxxxxx"
}
provider "google" {
project = "mygcpproject"
region  = "us-west1"
}
module "single-project-cspm" {
source               = "sysdiglabs/secure/google//modules/services/service-principal"
project_id           = "mygcpproject"
service_account_name = "ravina-test-sa"
}
resource "sysdig_secure_cloud_auth_account" "gcp_account_provider_id" {
provider_id   = "mygcpproject"
provider_type = "PROVIDER_GCP"
enabled       = true
feature {
secure_config_posture {
enabled    = "true" …
```
=> fix(secure-cloud-account): Support parsing JSON encoded string inputs for Component metadata

sysdig/resource_sysdig_secure_cloud_auth_account.go
----------------
Populating all the fields to fill in the GCP `service_principal_metadata` proto struct (and not just the required fields), since we want to store enough metadata information for potential usecases allowing us to run any future workflows.
=> Populate all fields of component metadata in Cloudauth Account resource

main.go, sysdig/internal/client/v2/config.go, sysdig/internal/client/v2/list.go, sysdig/internal/client/v2/macros.go, sysdig/internal/client/v2/policies.go, sysdig/internal/client/v2/rules.go, sysdig/provider.go, sysdig/resource_sysdig_secure_custom_policy.go, sysdig/resource_sysdig_secure_list.go, sysdig/resource_sysdig_secure_macro.go, sysdig/resource_sysdig_secure_managed_policy.go, sysdig/resource_sysdig_secure_managed_ruleset.go, sysdig/resource_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_rule_container.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_filesystem.go, sysdig/resource_sysdig_secure_rule_network.go, sysdig/resource_sysdig_secure_rule_process.go, sysdig/resource_sysdig_secure_rule_syscall.go, sysdig/sysdig_clients.go
when enabled, this new flag will not send a message to the agents with the new contents. applies to all policies/rules/lists/macro creates/deletes/updates
=> add option to skip policyv2msg in policy/rule/list/macro mutating operations

sysdig/internal/client/v2/cloudauth.go, sysdig/internal/client/v2/cloudauth_test.go, sysdig/resource_sysdig_secure_cloud_auth_account_test.go
----------------
1. Added tests for new cloudauth based CloudAccount resource.
2. Minor refactoring of marshal/unmarshal methods of cloudauth client.
3. Added the tests for the marshal/unmarshal methods.
=> Add Cloudauth Account resource Tests

sysdig/internal/client/v2/organization.go, website/docs/r/secure_organization.md
=> Remove provider_type from the org documentation

sysdig/internal/client/v2/cloudauth_test.go, sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_cloud_auth_account_test.go
Fixed and updated `TestAccSecureCloudAuthAccountFC` with `feature` and `component{}` payload in the resource request.
=> Uncomment and add TestAccSecureCloudAuthAccountFC

sysdig/resource_sysdig_team_service_account.go, sysdig/resource_sysdig_team_service_account_test.go, website/docs/r/team_service_account.md
The `api_key` was not set because the rest endpoint returns it only after resource creation.
In the old implementation a user was allowed to update only the service account `name` because the BE endpoint that handles the resource update accepts only the `name`.
Was introduced the `ForceNew` schema behaviour that when a field different than name is updated requires the resource to be destroyed and recreated.
=> fix(team-service-account):  api key not set 

sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_cloud_auth_account_test.go, sysdig/resource_sysdig_secure_organization_test.go
Fix summary:
--------------
Currently the provider reads and returns one of the fields in the resource schema with incorrect structure. This results in unexpected diff during terraform re-apply.
- Fixing the interface conversion during reads for the same.
- Also updated the acceptance tests accordingly to test this.
Testing done:
--------------
Validated this using TF Acceptance tests as well as e2e manually.
=> fix(secure-onboarding) Fixing the resource schema during reads

sysdig/data_source_sysdig_fargate_workload_agent.go, sysdig/data_source_sysdig_fargate_workload_agent_test.go, website/docs/d/fargate_workload_agent.md
Serverless Agent
This PR marks the access key as optional in the fargate workload agent data source.
Note that:
- the direct connection mode has been deprecated,
- and the workload agent does not require the access key to connect to the orchestrator agent.
=> fix(serverless-agent): mark the access key as optional

sysdig/common.go, sysdig/internal/client/v2/organization.go, sysdig/resource_sysdig_secure_organization.go, website/docs/r/secure_organization.md
* add `organizational_unit_ids` to the secure organization resource
=> feat(cloudauth): organizational units

sysdig/data_source_sysdig_secure_policy.go, sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_policy_test.go, website/docs/d/secure_custom_policy.md, website/docs/d/secure_managed_policy.md, website/docs/d/secure_managed_ruleset.md, website/docs/r/secure_custom_policy.md, website/docs/r/secure_managed_policy.md, website/docs/r/secure_managed_ruleset.md, website/docs/r/secure_policy.md
This PR adds support for the following three Secure Policy capture related optional fields:
- Filter (Filter string to reduce scope of a capture, eg. `proc.name=vi`)
- Bucket Name (to provide a custom S3 bucket to store the capture files)
- Folder (to provide a folder inside the S3 bucket)
=> Add support for Secure policy capture fields

sysdig/internal/client/v2/cloudauth.go, sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_cloud_auth_account_test.go
Fix summary:
-------------
Correctly manage the components state and key state
1. Updated the API call with query param.
2. Handling resource data to api objects and api objects to resource data conversions.
3. Handling decoding/encoding of keys and json conversions with proper indentation.
4. Refactored the structure to maintain order in the component schema list field as well as key fields.
5. Refactored some of the naming of methods and vars.
Testing done:
--------------
Validated with acceptance tests on staging and E2E tests.
=> fix(secure-onboarding) Fix component and key state

sysdig/resource_sysdig_secure_cloud_auth_account_test.go
=> (secure-onboarding) Enable acceptance test for Secure cloud account

sysdig/common.go, sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_cloud_auth_account_test.go
This PR is to pass `provider_alias` field as part of cloud account creation call to support org onboarding.
=> Pass provider alias to cloud account creation call

sysdig/internal/client/v2/model_dashboard.go, sysdig/resource_sysdig_monitor_dashboard.go, sysdig/resource_sysdig_monitor_dashboard_test.go
The resource `sysdig_monitor_dashboard` has the `panel.legend` and `panel.query.format` fields that are optional. If the user doesn't configure these fields, the provider initializes those with some default values.
Currently, if the user runs `terraform plan/apply` without a legend, or a query format, the provider always shows some diffs even if the dashboard was not changed.
This PR fixes the mapping in `resourceSysdigDashboardRead` to prevent these drifts.
=> fix(dashboards) prevent false drift with optional legend and query format

sysdig/internal/client/v2/cloudauth.go, sysdig/internal/client/v2/organization.go, sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_organization.go
Fix summary:
-------------
Currently any of the backend API errors are returned by the provider as: `"Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers."` This is not useful at all.
Hence, surfacing up the errors coming from backend during Create/Read/Update/Delete operations for `secure_cloud_auth_account` and `secure_organization` resources.
Currently:
```
sysdig_secure_cloud_auth_account.gcp_project_foo: Creating...
╷
│ Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.
```
With this change:
```
sysdig_secure_cloud_auth_account.gcp_project_foo: Creating...
╷
│ Error: Error creating resource: 409 Conflict {"error":"entity already …
```
=> (secure-onboarding) Handle and populate errors from secure backend

sysdig/data_source_sysdig_fargate_workload_agent.go, sysdig/testfiles/ECSInstrumented.json, sysdig/testfiles/fargate_bare_pdig_expected.json, sysdig/testfiles/fargate_cmd_test_expected.json, sysdig/testfiles/fargate_combined_test_expected.json, sysdig/testfiles/fargate_entrypoint_test_expected.json, sysdig/testfiles/fargate_env_test_expected.json, sysdig/testfiles/fargate_field_case_test_expected.json, sysdig/testfiles/fargate_ignore_container_test_expected.json, sysdig/testfiles/fargate_linuxparameters_test_expected.json, sysdig/testfiles/fargate_log_group_expected.json, sysdig/testfiles/fargate_volumesfrom_test_expected.json
=> new(serverless-agent): support sidecar mode (disabled by default)

sysdig/resource_sysdig_monitor_alert_common.go
`notification_channels` attribute is considered a set in the backend, we should also treat it as set in the terraform provider so that drifts are not wrongly reported like in this example: 
```
~ resource "sysdig_monitor_alert_metric" "alert" {
id                    = "44198694"
name                  = "test"
~ notification_channels = [
- 1610269,
1742117,
+ 1610269,
]
}
```
The underlying representation of list and set is the same in the state, so this is retro compatible.
=> fix(alerts): treat notification_channels as set

sysdig/internal/client/v2/alerts_v2.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus_test.go, sysdig/resource_sysdig_monitor_alert_v2_group_outlier.go, sysdig/resource_sysdig_monitor_alert_v2_group_outlier_test.go, website/docs/index.md, website/docs/r/monitor_alert_v2_group_outlier.md
add new alert type: `sysdig_monitor_alert_v2_group_outlier`, implementing the feature described in https://docs.sysdig.com/en/docs/sysdig-monitor/alerts/alert-types/group-outlier-alerts/.
=> feat(alerts): add group outlier alert type

.gitignore, sysdig/internal/client/v2/model_dashboard.go, sysdig/resource_sysdig_monitor_dashboard.go, sysdig/resource_sysdig_monitor_dashboard_test.go
=> feat(dashboards): configuring dashboard resource to accept min_interval

sysdig/resource_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_policy_test.go, sysdig/resource_sysdig_secure_rule_falco.go, sysdig/resource_sysdig_secure_rule_falco_test.go, website/docs/d/secure_custom_policy.md, website/docs/d/secure_managed_policy.md, website/docs/d/secure_managed_ruleset.md, website/docs/r/secure_custom_policy.md, website/docs/r/secure_managed_policy.md, website/docs/r/secure_managed_ruleset.md, website/docs/r/secure_policy.md, website/docs/r/secure_rule_falco.md
adding support for secure policy and rules of new falco cloud policy types, (awscloudtrail, okta, and github)
=> add support for awscloudtrail, okta, and github rules and policies

sysdig/resource_sysdig_secure_scanningpolicies.go, sysdig/resource_sysdig_secure_scanningpoliciesassignments.go, sysdig/resource_sysdig_secure_vulnerability_exception.go, sysdig/resource_sysdig_secure_vulnerability_exception_list.go, website/docs/r/secure_scanning_policy.md, website/docs/r/secure_scanning_policy_assignment.md, website/docs/r/secure_vulnerability_exception.md, website/docs/r/secure_vulnerability_exception_list.md
deprecate legacy scanning engine resources
=> feat(scanning): deprecate legacy scanning engine resources

sysdig/internal/client/v2/posture_zones.go, sysdig/resource_sysdig_secure_posture_zone.go
=> fix(zones) return http error message in create zone api ESC-4101

sysdig/resource_sysdig_secure_cloud_auth_account.go
fixes a bug where gcp keys were posted with an empty body when not in use, violating API data validity rules.
=> fix(cloudauth): create gcp key only when present

sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_cloud_auth_account_test.go
-----------------
1. Support for GCP CDR validation during onboarding using WIF. Mainly fixed the case for metadata population when WIF is passed.
2. Added GCP CDR tests.
3. Modified the structure and organization of acceptance test suite for sysdig_secure_cloud_auth_account resource.
Testing done:
---------------
- Validated this end to end using local TF sysdig provider plugin on staging.
- Validated the acceptance tests against staging.
=> feat(onboarding): Add validation support for GCP CDR onboarding

sysdig/data_source_sysdig_fargate_ECS_test.go, sysdig/data_source_sysdig_fargate_workload_agent.go, sysdig/testfiles/ECSInstrumented.json, sysdig/testfiles/fargate_bare_pdig_expected.json, sysdig/testfiles/fargate_cmd_test_expected.json, sysdig/testfiles/fargate_combined_test_expected.json, sysdig/testfiles/fargate_entrypoint_test_expected.json, sysdig/testfiles/fargate_env_test_expected.json, sysdig/testfiles/fargate_field_case_test_expected.json, sysdig/testfiles/fargate_ignore_container_test_expected.json, sysdig/testfiles/fargate_linuxparameters_test_expected.json, sysdig/testfiles/fargate_log_group_expected.json, sysdig/testfiles/fargate_volumesfrom_test_expected.json
=> serverless-agent: expose priorities control

sysdig/data_source_sysdig_secure_policy.go, sysdig/resource_sysdig_secure_custom_policy.go, sysdig/resource_sysdig_secure_custom_policy_test.go
=> Rules order in policy showing drift during apply

sysdig/resource_sysdig_secure_cloud_auth_account.go
fixes an issue where, during the resource planning phase, cloudauth component set members were not being correctly identified, producing differences during planning where no-op changes were expected.
Adding a default value (empty string) for the unset component metadata field members allows these resources to be considered "equivalent" or "compatible" in terraform parlance.
=> fix(cloudauth): component metadata diff

sysdig/data_source_sysdig_secure_aws_ml_policy_test.go, sysdig/data_source_sysdig_secure_drift_policy_test.go, sysdig/data_source_sysdig_secure_malware_policy_test.go, sysdig/data_source_sysdig_secure_ml_policy_test.go, sysdig/resource_sysdig_secure_aws_ml_policy_test.go, sysdig/resource_sysdig_secure_drift_policy_test.go, sysdig/resource_sysdig_secure_malware_policy_test.go, sysdig/resource_sysdig_secure_ml_policy_test.go
- Create new build tag "tf_acc_policies_aws" so these will not be built during IBM test runs
- Needs to be combined with a PR for Jenkins job to use the new build tag for AWS, IBM will continue using existing tags
=> (Internal) Skip unsupported policy types on IBM

sysdig/internal/client/v2/alerts_v2.go, sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_monitor_alert_v2_downtime.go
An alert of type downtime is actually an alert of type manual with specific aggregations on specific metrics, so, to create a downtime alert, we could use either the manual alert type or the more specific downtime alert type.
This is no true anymore with recent changes in the v2 api. This PR fixes the problem using the correct alert type for the downtime alerts.
=> fix(alerts): use correct type un api for downtime alerts

sysdig/common.go, sysdig/internal/client/v2/cloudauth_account_component.go, sysdig/internal/client/v2/cloudauth_account_feature.go, sysdig/internal/client/v2/model.go, sysdig/internal/client/v2/sysdig.go, sysdig/provider.go, sysdig/resource_sysdig_secure_cloud_auth_account.go, sysdig/resource_sysdig_secure_cloud_auth_account_component.go, sysdig/resource_sysdig_secure_cloud_auth_account_feature.go, sysdig/resource_sysdig_secure_cloud_auth_account_feature_test.go, website/docs/r/secure_cloud_auth_account_feature.md
-------------------
- Adding new Account Feature resource with schema and CRUD operations
in parity with Cloudauth Account and AccountComponent resource.
- Adding the respective client and support for new resource type.
- Added TF ACC tests for the new resource type.
- Added docs md for the new resource.
=> feat(secure-onboarding): Adding AccountFeature Resource

sysdig/data_source_sysdig_secure_notification_channel_team_email_test.go, sysdig/internal/client/v2/client.go, sysdig/internal/client/v2/client_test.go
Sysdig APIs are not perfectly standardised, so several errors at the moment are not well handled: in such cases, if the body is still json, the `ErrorFromResponse` function returns an empty error that is not handled properly by the terraform sdk leading to a misleading message:
```
X-Content-Type-Options: nosniff
{
"timestamp" : 1715251965029,
"status" : 401,
"error" : "Unauthorized",
"path" : "/api/v2/alerts/46667521"
}: timestamp=2024-05-09T12:52:45.008+0200
2024-05-09T12:52:45.009+0200 [ERROR] provider.terraform-provider-sysdig: Response contains error diagnostic: diagnostic_severity=ERROR tf_proto_version=5.3 tf_req_id=e2629c9f-bc17-9008-98b7-40215d63dfc0 tf_resource_type=sysdig_monitor_alert_v2_downtime diagnostic_detail= diagnostic_summary="Empty Summary: This is always a bug in the …
```
=> fix(client): correctly handle nonstandard json errors

sysdig/data_source_sysdig_secure_aws_ml_policy_test.go, sysdig/data_source_sysdig_secure_trusted_cloud_identity_test.go, sysdig/resource_sysdig_secure_aws_ml_policy_test.go, sysdig/resource_sysdig_secure_custom_policy.go, sysdig/resource_sysdig_secure_custom_policy_test.go, sysdig/resource_sysdig_secure_policy_test.go
* Do not run cloud policy types tests with `tf_acc_onprem_secure` tag
* Use TypeSet instead of TypeList for rules
=> fix(tests): Skip onprem unsupported policy types

sysdig/internal/client/v2/model.go, sysdig/internal/client/v2/posture_policies.go, sysdig/resource_sysdig_secure_posture_policy.go, sysdig/resource_sysdig_secure_posture_policy_test.go
we change get policy to get full policy. that api will return policy with requirement folders, requirements and controls (that are linked to requirement). to be align with create and update we change the response to be the same to get create and update policy. this task in JIRA: https://sysdig.atlassian.net/browse/SSPROD-41907
=> ssprod_41907 | add get full policy

website/docs/r/group_mapping.md
Clarify how to use the resources by providing additional examples.
=> fix(group-mapping): Improve the documentation

sysdig/resource_sysdig_monitor_notification_channel_team_email_test.go, sysdig/resource_sysdig_secure_notification_channel_team_email_test.go
the team resources seem to suffer of slight caching problems on our tests envs, fix unit tests on notification channels resources by not updating teams but always creating new ones.
=> fix(notificationchannel): fix flaky tests

.github/workflows/release.yml
tagged releases appear to be broken due to deprecation of a goreleaser argument. Here is an example:
https://github.com/sysdiglabs/terraform-provider-sysdig/actions/runs/9490299875/job/26153499539
This PR updates the goreleaser action and removes the deprecated argument
=> fix(gha): gorelease action args

sysdig/internal/client/v2/model.go
=> fix access key by ommiting both limit and reservation when not specified

sysdig/resource_sysdig_monitor_alert_v2_common.go, sysdig/resource_sysdig_monitor_alert_v2_metric_test.go
In the alerts v2 api, [Info](https://docs.sysdig.com/en/docs/sysdig-monitor/alerts/configure-alerts/#settings) severity is actually defined via the value "none", here we fix this case.
The severity value in the terraform resources is also accepted regardless of casing (same as the alerts v2 api), but using non-lowercase characters leads to plan drifts, here we ignore diffs in such situations.
=> fix(alerts): properly handle info severity

sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus.go, sysdig/resource_sysdig_monitor_alert_v2_form_based_prometheus_test.go, website/docs/r/monitor_alert_v2_form_based_prometheus.md
For form based prometheus alerts, the operator to check equality is `==`, not `=`. We fix this bug in this PR.
This is slightly inconsistent with the operator in metric alerts, that uses `=` but still we use `==` because the tf resources should be as close as possible to the underlying apis.
Note that this is not really a breaking change because the old `=` never worked.
=> fix(alerts): fix operator for form based prometheus alerts

sysdig/resource_sysdig_secure_cloud_auth_account.go
These errors should not be swallowed. they are legitimate and should be bubbled up. Leaving the 404 swallow for the delete case since it also represents success on a delete operation
=> fix(cloudauth): remove 404 error swallow

CODEOWNERS, sysdig/internal/client/v2/client.go, sysdig/internal/client/v2/inhibition_rule.go, sysdig/internal/client/v2/model.go, sysdig/provider.go, sysdig/resource_sysdig_monitor_alert_v2_common.go, sysdig/resource_sysdig_monitor_alert_v2_metric_test.go, sysdig/resource_sysdig_monitor_inhibition_rule.go, sysdig/resource_sysdig_monitor_inhibition_rule_test.go, website/docs/index.md, website/docs/r/monitor_alert_v2_change.md, website/docs/r/monitor_alert_v2_downtime.md, website/docs/r/monitor_alert_v2_event.md, website/docs/r/monitor_alert_v2_form_based_prometheus.md, website/docs/r/monitor_alert_v2_group_outlier.md, website/docs/r/monitor_alert_v2_metric.md, website/docs/r/monitor_alert_v2_prometheus.md, website/docs/r/monitor_inhibition_rule.md
* add resource to manage Inhibition rules
* add new field to attach labels to alerts
=> feat(monitor): add resource to manage Inhibition rules

sysdig/resource_sysdig_monitor_alert_v2_downtime.go, sysdig/resource_sysdig_monitor_alert_v2_event.go, sysdig/resource_sysdig_monitor_alert_v2_metric.go, sysdig/resource_sysdig_monitor_alert_v2_prometheus.go, website/docs/r/monitor_alert_v2_form_based_prometheus.md, website/docs/r/monitor_alert_v2_metric.md
=> chore(alerts): fix doc

sysdig/cfn_preprocess_template.go
This PR fixes govet error showing in regression CI builds.
=> fix(ci): fix govet error

sysdig/resource_sysdig_secure_policy_test.go
Fixes #549, as `buildinfo` contains the info about the test suite, not the target env.
=> fix(tests): Proper check to determine if env is IBM

sysdig/resource_sysdig_ip_filter_test.go
=> fix ip_filter acc test - delete resource after creation to avoid conflict

sysdig/resource_sysdig_secure_posture_control_test.go
This test should not be run against an onprem environment
=> fix: Do not run custom control resource test in onprem

sysdig/resource_sysdig_monitor_cloud_account.go
Monitor Cloud account config has an issue with the role name delegation parameter.
Once the resource is created and it's run again, the unchanged parameter rolename has conflicts with the name that we request with the provider. The one of the provider has the full ARN name as suffix of the role name parameter. So, we fix that with this PR.
=> fix(cloudauth-monitor): ADD format logic to get role name param

sysdig/data_source_sysdig_secure_onboarding.go, sysdig/data_source_sysdig_secure_onboarding_test.go, website/docs/d/secure_cloud_ingestion_assets.md
----------------
1. Reading and returning new field EB ARN Gov for regulatory workloads such as aws gov workloads.
2. Updated the acc test and docs.
=> feat(onboarding): Adding regulatory EB ARN to cloud ingestion datasource

sysdig/resource_sysdig_secure_rule_falco_test.go
=> [SSPROD-49510] Use unique names for parallel tests

sysdig/data_source_sysdig_secure_rule_falco_count_test.go, sysdig/data_source_sysdig_secure_rule_falco_test.go, sysdig/resource_sysdig_secure_list_test.go, sysdig/resource_sysdig_secure_macro_test.go, sysdig/resource_sysdig_secure_rule_falco_test.go
Some of these Falco tests using identical names can interfere with each other when run in parallel
=> [SSPROD-49510] - Make some falco tests run in serial mode

sysdig/resource_sysdig_secure_rule_falco_test.go
=> Break up the tests to make it easier to debug

sysdig/data_source_sysdig_secure_onboarding.go, sysdig/data_source_sysdig_secure_onboarding_test.go, sysdig/internal/client/v2/onboarding.go, sysdig/provider.go, website/docs/d/secure_trusted_oracle_app.md
----------------
- Adding new datasource secure_trusted_oracle_app to fetch OCI trusted identity per app group.
- Added acc tests and docs for the new datasource.
=> feat(onboarding): Datasource for OCI Trusted app group

examples/serverless-agent/fargate/workload-legacy/README.md, examples/serverless-agent/fargate/workload-legacy/instrumented_load.tf, examples/serverless-agent/fargate/workload-legacy/output.tf, examples/serverless-agent/fargate/workload-legacy/providers.tf, examples/serverless-agent/fargate/workload-legacy/variables.tf, examples/serverless-agent/fargate/workload-legacy/versions.tf
This is the new default deployment mode.
=> feat(examples): Add Serverless Agent direct connection example

website/docs/d/fargate_workload_agent.md
This PR updates the documentation of the fargate workload agent data source. The orchestrator agent is no longer required.
=> docs(serverless): the workload agent no longer requires the orchestrator

sysdig/data_source_sysdig_secure_onboarding.go, sysdig/data_source_sysdig_secure_onboarding_test.go, sysdig/internal/client/v2/onboarding.go, website/docs/d/secure_cloud_ingestion_assets.md
- data_source_sysdig_secure_onboarding.go: Added parameters and updated the API request for cloud provider and provider ID.
- data_source_sysdig_secure_onboarding_test.go: Added tests for the new cloud provider parameter and error handling.
- onboarding.go: Modified the API request to include cloud provider and provider ID.
- secure_cloud_ingestion_assets.md: Updated documentation to reflect new fields for cloud ingestion assets.
=>  feat(cloudtrail): add support for SNS ingestion

go.mod, go.sum
Solves:
- CVE-2024-41110
- CVE-2024-24557
- GHSA-jq35-85cj-fj4p
=> fix: update dependencies to solve vulnerabilities

sysdig/data_source_sysdig_monitor_notification_channel_msteams_test.go, sysdig/data_source_sysdig_monitor_notification_channel_slack_test.go, sysdig/data_source_sysdig_secure_notification_channel_msteams_test.go, sysdig/data_source_sysdig_secure_notification_channel_slack_test.go, sysdig/resource_sysdig_monitor_notification_channel_msteams_test.go, sysdig/resource_sysdig_monitor_notification_channel_slack_test.go, sysdig/resource_sysdig_secure_notification_channel_msteams_test.go, sysdig/resource_sysdig_secure_notification_channel_slack_test.go, website/docs/r/monitor_notification_channel_slack.md, website/docs/r/secure_notification_channel_slack.md
Tests for msteams and slack notification channels are using invalid urls for the channel webhooks. 
Now that we've added validation of urls on the BE, the tests should be updated to use valid urls.
=> fix(notification-channels) Update the terraform tests to account for the notification channel url validation

sysdig/internal/client/v2/model.go, sysdig/resource_sysdig_secure_drift_policy.go, sysdig/resource_sysdig_secure_drift_policy_test.go, sysdig/tfresource.go, website/docs/r/secure_drift_policy.md
Work for following issue:
https://github.com/sysdiglabs/terraform-provider-sysdig/issues/572
=> feat(drift-policies): add process based exceptions to drift policies

sysdig/resource_sysdig_secure_managed_policy_test.go, sysdig/resource_sysdig_secure_managed_ruleset_test.go, website/docs/r/secure_managed_policy.md, website/docs/r/secure_managed_ruleset.md
The old rule was removed from this managed policy
=> fix(policies) switch out rule in managed secure policy tests

sysdig/data_source_sysdig_monitor_notification_channel_slack.go, sysdig/data_source_sysdig_secure_notification_channel_slack.go, sysdig/resource_sysdig_monitor_notification_channel_slack.go, sysdig/resource_sysdig_secure_notification_channel_slack.go
Slack webhook URLs are sensitive according to Slack documentation (https://api.slack.com/messaging/webhooks):
> Keep it secret, keep it safe. Your webhook URL contains a secret. Don't share it online, including via public version control repositories. Slack actively searches out and revokes leaked secrets.
This PR makes them sensitive in Terraform as well so they don't get sent to logs and unexpectedly exposed.
=> chore(notification-channels): Make Slack webhook URL fields sensitive

sysdig/internal/client/v2/posture_controls.go, sysdig/internal/client/v2/posture_policies.go, sysdig/internal/client/v2/posture_zones.go, sysdig/internal/client/v2/zones.go
correctly handle api errors in several GET calls so that a proper message is shown, rather than a parsing issue. 
Fixes https://github.com/sysdiglabs/terraform-provider-sysdig/issues/617.
=> fix(posture/zones): correctly handle api errors

sysdig/resource_sysdig_secure_accept_posture_risk.go, sysdig/resource_sysdig_secure_accept_posture_risk_test.go
=> fix(posture/accept-risk): allow `expires_in=Never` value

sysdig/resource_sysdig_secure_cloud_auth_account_test.go
Latest changes in backend shows the components of the cloud auth resource reordered. This is consistent now, but the test was failing. This may fail for customers as well, complaining that the resources now show differences where there should be none. This comment is also documenting that future issue...
=> fix(ci): reorder elements in test
