sysdiglabs/terraform-provider-sysdig

examples/create-secure-policy/main.tf
sysdig/provider.go
sysdig/resource_sysdig_secure_notification_channel.go
sysdig/resource_sysdig_secure_policies_priority.go
sysdig/resource_sysdig_secure_policy.go
sysdig/sysdig_secure_client.go
sysdig/sysdig_secure_client_test.go
sysdig/sysdig_secure_models.go

Fix in Notification Channels that changed from String to Integer in the API and wasn't being recognized.
Added priority resource for policies.
The policies created in Terraform will have more priority than the ones created via UI.

Fix channel per policy and add priority

---

examples/create-secure-policy/main.tf
scripts/oanc/Dockerfile
scripts/oanc/docker-compose.yaml
scripts/oanc/main.go
sysdig/provider.go
sysdig/resource_sysdig_secure_notification_channel.go
sysdig/resource_sysdig_secure_policies_priority.go
sysdig/resource_sysdig_secure_policy.go
sysdig/sysdig_secure_client.go
sysdig/sysdig_secure_client_test.go
sysdig/sysdig_secure_models.go

Added oanc (which stands for OAuth Notification Channel) script to retrieve the resource information from OAuth Notification Channels like Slack that must be created from UI.

Add oanc script

---

examples/create-secure-policy/main.tf
sysdig/resource_sysdig_secure_policy.go
sysdig/sysdig_secure_models.go

Added support for the following Secure UI rules via Terraform rules and some examples:
- Processes
- Containers
- Network
- Filesystem
- Syscalls

Secure UI rules

---

examples/user.tf
sysdig/provider.go
sysdig/resource_sysdig_user.go
sysdig/resource_sysdig_user_test.go
sysdig/secure/client.go
sysdig/secure/models.go
sysdig/secure/users.go

Signed-off-by: Hiroki Suezawa <suezawa@gmail.com>
- Add sysdig_user resource (Sorry for a big PR)
- This PR is related to #11 
- I would like to add `sysdig_secure_team` too, but this PR has `user` only.
- I used `terraform-test@sysdig.com` for testing for now. but Does Sysdig have e-mail address for testing?

Add sysdig_user resource

---

sysdig/resource_sysdig_user_test.go

- change `resource_sysdig_user_test.go`
- Doesn't change email address in each step. 
- test on #12 was failed.
- (I thought it passed once, but it failed today. sorry.)

Modify test for sysdig_user

---

.github/workflows/release.yml
.goreleaser.yml

This PR adds the release procedure specified in the [Terraform Registry documentation](https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-)

ci: Add Terraform Registry release procedure

---

go.mod
sysdig/helpers.go
sysdig/monitor/client.go
sysdig/monitor/dashboards.go
sysdig/monitor/models.go
sysdig/provider.go
sysdig/resource_sysdig_monitor_dashboard.go
sysdig/resource_sysdig_monitor_dashboard_test.go

This PR adds the initial support for Dashboard v3 creation as resource.

feat: Initial support for Dashboards v3

---

sysdig/internal/client/monitor/model/dashboard.go
sysdig/resource_sysdig_monitor_dashboard.go
sysdig/resource_sysdig_monitor_dashboard_test.go
website/docs/r/sysdig_monitor_dashboard.md

This PR adds support for Text panel type.

feat: Support more panel types

---

sysdig/data_source_sysdig_user.go
sysdig/data_source_sysdig_user_test.go
sysdig/internal/client/common/client.go
sysdig/internal/client/common/users.go
sysdig/provider.go
sysdig/resource_sysdig_user.go
website/docs/d/sysdig_user.md
website/sysdig.erb

Adds the `sysdig_user` data source that retrieves information from the user via their email.

feat: Add Sysdig User datasource

---

sysdig/internal/client/secure/client.go
sysdig/internal/client/secure/models.go
sysdig/internal/client/secure/vulnerability_exception.go
sysdig/provider.go
sysdig/resource_sysdig_secure_vulnerability_exception.go
sysdig/resource_sysdig_secure_vulnerability_exception_list.go
sysdig/resource_sysdig_secure_vulnerability_exception_list_test.go
sysdig/resource_sysdig_secure_vulnerability_exception_test.go
website/docs/r/sysdig_secure_vulnerability_exception.md
website/docs/r/sysdig_secure_vulnerability_exception_list.md
website/sysdig.erb

This PR adds the `sysdig_secure_vulnerability_exception` and `sysdig_secure_vulnerability_exception_list` resources, to manage the Vulnerability exceptions as code.

feat: Vulnerability exception resources

---

sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
sysdig/resource_sysdig_secure_notification_channel_webhook_test.go
website/docs/index.md
website/docs/r/sysdig_monitor_alert_anomaly.md
website/docs/r/sysdig_monitor_alert_downtime.md
website/docs/r/sysdig_monitor_alert_event.md
website/docs/r/sysdig_monitor_alert_group_outlier.md
website/docs/r/sysdig_monitor_alert_metric.md
website/docs/r/sysdig_monitor_notification_channel_email.md
website/docs/r/sysdig_monitor_notification_channel_opsgenie.md
website/docs/r/sysdig_monitor_notification_channel_pagerduty.md
website/docs/r/sysdig_monitor_notification_channel_slack.md
website/docs/r/sysdig_monitor_notification_channel_sns.md
website/docs/r/sysdig_monitor_notification_channel_victorops.md
website/docs/r/sysdig_monitor_notification_channel_webhook.md
website/docs/r/sysdig_monitor_team.md
website/docs/r/sysdig_secure_notification_channel_email.md
website/docs/r/sysdig_secure_notification_channel_opsgenie.md
website/docs/r/sysdig_secure_notification_channel_pagerduty.md
website/docs/r/sysdig_secure_notification_channel_slack.md
website/docs/r/sysdig_secure_notification_channel_sns.md
website/docs/r/sysdig_secure_notification_channel_victorops.md
website/docs/r/sysdig_secure_notification_channel_webhook.md
website/docs/r/sysdig_secure_team.md

docs: Update some resources in the documentation

---

sysdig/internal/client/monitor/model/dashboard.go
sysdig/resource_sysdig_monitor_dashboard.go
sysdig/resource_sysdig_monitor_dashboard_test.go
website/docs/r/monitor_dashboard.md

Add ability to set dashboard sharing options

---

sysdig/data_source_sysdig_monitor_notification_channel_email.go
sysdig/data_source_sysdig_monitor_notification_channel_email_test.go
sysdig/data_source_sysdig_monitor_notification_channel_pagerduty.go
sysdig/data_source_sysdig_monitor_notification_channel_pagerduty_test.go
sysdig/provider.go
website/docs/d/monitor_notification_channel_email.md
website/docs/d/monitor_notification_channel_pagerduty.md

Add data sources for PagerDuty and email notification channels

---

.envrc.template
.gitignore
README.md
sysdig/data_source_sysdig_secure_current_connection.go
sysdig/data_source_sysdig_secure_current_connection_test.go
sysdig/provider.go
sysdig/sysdig_clients.go
website/docs/d/secure_connection.md

in order terraform modules to be able to infer the secure endpoint/apiKey from the provider.
this will deprecate current module input vars

feat: add datasource secure connection

---

.github/workflows/issues-slack-notify.yml

Add an action to notify Slack when an issue is created

chore: add issue opened slack notification action

---

sysdig/cfn_preprocess_template.go
sysdig/data_source_sysdig_fargate_ECS_test.go
sysdig/data_source_sysdig_fargate_workload_agent.go
sysdig/testfiles/ECSinput.json
sysdig/testfiles/fargate_cmd_test.json
sysdig/testfiles/fargate_cmd_test_expected.json
sysdig/testfiles/fargate_combined_test.json
sysdig/testfiles/fargate_combined_test_expected.json
sysdig/testfiles/fargate_entrypoint_test.json
sysdig/testfiles/fargate_entrypoint_test_expected.json
sysdig/testfiles/fargate_env_test.json
sysdig/testfiles/fargate_env_test_expected.json
sysdig/testfiles/fargate_linuxparameters_test.json
sysdig/testfiles/fargate_linuxparameters_test_expected.json

https://sysdig.atlassian.net/browse/SMAGENT-3875
If there are keys that we know to be used by Kilt, those will be converted to Cloudformation JSON syntax, which essentially just means capitalized keys names, before being passed to the patcher.
Also adds some more test coverage specifically around the conversion.

fix: json casing

---

sysdig/data_source_sysdig_fargate_ECS_test.go
sysdig/testfiles/fargate_volumesfrom_test.json
sysdig/testfiles/fargate_volumesfrom_test_expected.json

Added additional testcase to check if 'volumesfrom' field is modified correctly by Terraform provider

Volumesfrom additional testcase

---

CODEOWNERS

chore: fix fargate codeowners

---

sysdig/resource_sysdig_secure_rule_falco.go
sysdig/resource_sysdig_secure_rule_falco_test.go

This fix more generally lifts the requirement for a condition if append: true

fix: Modify to not require condition if append: true

---

CODEOWNERS
sysdig/internal/client/monitor/alerts_v2.go
sysdig/internal/client/monitor/client.go
sysdig/internal/client/monitor/models_v2.go
sysdig/provider.go
sysdig/resource_sysdig_monitor_alert_v2_common.go
sysdig/resource_sysdig_monitor_alert_v2_downtime.go
sysdig/resource_sysdig_monitor_alert_v2_downtime_test.go
sysdig/resource_sysdig_monitor_alert_v2_event.go
sysdig/resource_sysdig_monitor_alert_v2_event_test.go
sysdig/resource_sysdig_monitor_alert_v2_metric.go
sysdig/resource_sysdig_monitor_alert_v2_metric_test.go
sysdig/resource_sysdig_monitor_alert_v2_prometheus.go
website/docs/r/monitor_alert_promql.md
website/docs/r/monitor_alert_v2_downtime.md
website/docs/r/monitor_alert_v2_event.md
website/docs/r/monitor_alert_v2_metric.md
website/docs/r/monitor_alert_v2_prometheus.md

Complete the work of implementing the new alert v2 resources started with https://github.com/sysdiglabs/terraform-provider-sysdig/pull/194.

feat: add support for alerts v2 

---

CODEOWNERS
sysdig/resource_sysdig_secure_policy.go
sysdig/resource_sysdig_secure_policy_test.go

Make capture attribute required for policy resource

---

.github/workflows/ci-pull-request.yml
.github/workflows/release.yml
README.md

docs: clarify acc tests in production

---

.github/workflows/ci-scheduled-tests.yml
.github/workflows/issues-slack-notify.yml

ci: scheduled regresion tests on sysdig backend

---

sysdig/resource_sysdig_secure_vulnerability_exception_test.go

fix: expiration_date past date

---

.github/workflows/ci-scheduled-tests.yml

fix the `if` to launch the scheduled provider tests

ci: fix schedule conditional

---

CODEOWNERS

This PR updates the *fargate* code owners.

chore: remove unreachable codeowner

---

sysdig/internal/client/monitor/models.go
sysdig/internal/client/secure/models.go
sysdig/resource_sysdig_monitor_notification_channel_opsgenie.go
sysdig/resource_sysdig_monitor_notification_channel_opsgenie_test.go
sysdig/resource_sysdig_secure_notification_channel_opsgenie.go
sysdig/resource_sysdig_secure_notification_channel_opsgenie_test.go
website/docs/r/monitor_notification_channel_opsgenie.md
website/docs/r/secure_notification_channel_opsgenie.md

Add option to specify the region of the OpsGenie service.

feat(monitor,secure): support different regions for opsgenie notification channel

---

.github/workflows/ci-scheduled-tests.yml

select final slack notifier with minimum design, and start reporting to official support channel

SSPROD-21160 ci: update regresion test notificator

---

sysdig/internal/client/monitor/models_v2.go
sysdig/resource_sysdig_monitor_alert_v2_common.go
sysdig/resource_sysdig_monitor_alert_v2_metric_test.go
website/docs/r/monitor_alert_v2_downtime.md
website/docs/r/monitor_alert_v2_event.md
website/docs/r/monitor_alert_v2_metric.md
website/docs/r/monitor_alert_v2_prometheus.md

Support option to toggle notification on alert resolution.

feat(monitor): support notify_on_resolve option in alerts

---

sysdig/internal/client/secure/client.go
sysdig/internal/client/secure/policies.go
sysdig/resource_sysdig_secure_policy.go

Fix Issue With Handling Missing Policy

---

sysdig/resource_sysdig_secure_rule_falco_test.go

This PR fixes the tests by ensuring that the required description field is included.

add description to rule as falco validation requires a description

---

sysdig/internal/client/secure/client.go
sysdig/resource_sysdig_secure_rule_falco_test.go

Add Provider Header to All Secure Requests

---

website/docs/r/monitor_alert_v2_prometheus.md

add correct example for `sysdig_monitor_alert_v2_prometheus` resource.

docs: fix bad example

---

GNUmakefile
sysdig/resource_sysdig_secure_list_test.go
sysdig/resource_sysdig_secure_macro_test.go
sysdig/resource_sysdig_secure_notification_channel_email_test.go
sysdig/resource_sysdig_secure_policy_test.go
sysdig/resource_sysdig_secure_rule_container_test.go
sysdig/resource_sysdig_secure_rule_falco_test.go
sysdig/resource_sysdig_secure_rule_filesystem_test.go
sysdig/resource_sysdig_secure_rule_network_test.go
sysdig/resource_sysdig_secure_rule_process_test.go
sysdig/resource_sysdig_secure_rule_syscall_test.go
sysdig/resource_sysdig_secure_scanningpolicies_test.go
sysdig/resource_sysdig_secure_scanningpoliciesassignments_test.go
sysdig/resource_sysdig_secure_vulnerability_exception_list_test.go
sysdig/resource_sysdig_secure_vulnerability_exception_test.go

feat(acc_tests): Adding the possibility to run only certain tests per service for Secure parts for now

---

.goreleaser.yml
buildinfo/info.go
main.go
sysdig/internal/client/v2/client.go
sysdig/internal/client/v2/client_test.go
sysdig/internal/client/v2/ibm_test.go
sysdig/internal/client/v2/sysdig_test.go

Added `User-Agent` header on each HTTP request made by terraform provider.

User agent

---

GNUmakefile

The make junit report was not working properly. With this commit i am improving the output and we should be good when something happens.

(tests) Fix problems with the make junit-report

---

docs/index.md

Edit slack url hook in documentation.

fix(docs): edit slack url

---

.github/workflows/test.yml

Change testing environment for IBM from staging to production.

feat(test): change ibm tests from staging to prod

---

website/docs/r/secure_rule_syscall.md

Related PR: https://github.com/sysdiglabs/terraform-provider-sysdig/pull/313

fix(docs): fix copy-paste error in docs

---

sysdig/resource_sysdig_monitor_alert_v2_downtime_test.go
sysdig/resource_sysdig_monitor_alert_v2_metric_test.go

change tests to address segment limits in testing envs.

fix(monitor alerts): fix tests

---

CODEOWNERS
sysdig/internal/client/v2/model.go
sysdig/resource_sysdig_group_mapping.go
sysdig/resource_sysdig_group_mapping_test.go
website/docs/r/group_mapping.md

Changes made in the PR:
* Added Weight attribute
* Updated tests
* Updated documnetation

refactor(group mapping): added weigh to group mapping resource

---

sysdig/resource_sysdig_monitor_cloud_account_test.go

fix(cloud-acocunts) remove test expected empty plan

---

sysdig/internal/client/v2/group_mapping_config.go
sysdig/internal/client/v2/model.go
sysdig/internal/client/v2/sysdig.go
sysdig/provider.go
sysdig/resource_sysdig_group_mapping_config.go
sysdig/resource_sysdig_group_mapping_config_test.go
website/docs/r/group_mapping_config.md

Changes made in the PR:
This PR adds support for managing group mapping conflicts resolution configuration ([doc](https://docs.sysdig.com/en/docs/administration/administration-settings/user-and-team-administration/group-mappings/#group-mapping-behavior)): 
* created new resource `sysdig_group_mapping_config` this configuration is global per customer
* acceptance tests
* documentation

feat(group mapping): added new `group_mapping_config` resource

---

CODEOWNERS

This PR updates the CODEOWNERS.

chore(repo): update CODEOWNERS

---

website/docs/r/secure_custom_policy.md
website/docs/r/secure_managed_policy.md
website/docs/r/secure_managed_ruleset.md
website/docs/r/secure_policy.md

This PR updates the documentation for the policy resources to provide better examples for pulling the notification channels using a data source.

docs(policies): update docs to provide better examples

---

website/docs/r/monitor_alert_v2_downtime.md
website/docs/r/monitor_alert_v2_event.md
website/docs/r/monitor_alert_v2_metric.md
website/docs/r/monitor_alert_v2_prometheus.md

chore(alerts): fix typo in docs

---

sysdig/internal/client/v2/alerts_v2.go
sysdig/internal/client/v2/model.go
sysdig/provider.go
sysdig/resource_sysdig_monitor_alert_v2_change.go
sysdig/resource_sysdig_monitor_alert_v2_change_test.go
sysdig/resource_sysdig_monitor_alert_v2_common.go
sysdig/resource_sysdig_monitor_alert_v2_downtime.go
sysdig/resource_sysdig_monitor_alert_v2_event.go
sysdig/resource_sysdig_monitor_alert_v2_metric.go
sysdig/resource_sysdig_monitor_alert_v2_prometheus.go
website/docs/index.md
website/docs/r/monitor_alert_anomaly.md
website/docs/r/monitor_alert_downtime.md
website/docs/r/monitor_alert_event.md
website/docs/r/monitor_alert_group_outlier.md
website/docs/r/monitor_alert_metric.md
website/docs/r/monitor_alert_promql.md
website/docs/r/monitor_alert_v2_change.md
website/docs/r/monitor_alert_v2_downtime.md
website/docs/r/monitor_alert_v2_metric.md
website/docs/r/monitor_alert_v2_prometheus.md

add new alert type: `sysdig_monitor_alert_v2_change`, implementing the feature described in https://docs.sysdig.com/en/docs/sysdig-monitor/alerts/alert-types/change-alerts/.

feat(alerts): add change alert type

---

sysdig/resource_sysdig_monitor_cloud_account_test.go

fix(cloud-acocunts) test expect non empty plan

---

sysdig/common.go
sysdig/internal/client/v2/organization.go
sysdig/internal/client/v2/organization_test.go
sysdig/resource_sysdig_secure_cloud_auth_account.go
sysdig/resource_sysdig_secure_organization.go
sysdig/resource_sysdig_secure_organization_test.go
website/docs/r/secure_organization.md

Add support for Organization onboarding tests

---

sysdig/internal/client/v2/organization.go
sysdig/resource_sysdig_secure_organization_test.go

Update Org onboarding test with account creation

---

website/docs/r/secure_cloud_auth_account.md

Add Cloudauth Account resource Documentation

---

sysdig/internal/client/v2/organization.go
sysdig/resource_sysdig_secure_organization.go
sysdig/resource_sysdig_secure_organization_test.go

Removing the provider_type from org resource

---

sysdig/resource_sysdig_secure_cloud_auth_account.go

fix(secure-onboarding) Fix variable initialization during cloudaccount feature reads

---

sysdig/resource_sysdig_secure_posture_zone.go

fix(zones) Change Zone policy_ids schema to set instead of array ESC-3907

---

sysdig/resource_sysdig_secure_cloud_auth_account_test.go

This PR is a minor refactor to remove quotes for boolean values in acceptance tests.

Remove quotes for boolean values

---

CODEOWNERS

Update dashboards code owners

---

website/docs/r/secure_posture_zone.md

ESC-4101 - Update secure_posture_zone.md

---

sysdig/tfresource.go

cannot merge other prs (example: https://github.com/sysdiglabs/terraform-provider-sysdig/actions/runs/8110180227/job/22166893742?pr=481)  due to this.
blaming PR merge seems to have been force https://github.com/sysdiglabs/terraform-provider-sysdig/pull/476

fix(ci): lint

---

sysdig/resource_sysdig_secure_managed_policy_test.go
sysdig/resource_sysdig_secure_managed_ruleset_test.go
website/docs/r/secure_managed_policy.md
website/docs/r/secure_managed_ruleset.md

internal(policies) fix policies test: switch out rule in managed policy

---

sysdig/data_source_sysdig_secure_policy.go
sysdig/resource_sysdig_secure_custom_policy.go

ignore changes in policy rule ordering 

---

sysdig/internal/client/v2/posture_policies.go
sysdig/resource_sysdig_secure_posture_policy.go

delete posture policy: https://sysdig.atlassian.net/browse/SSPROD-39114

SSPROD-39114 | add delete policy 

---

sysdig/data_source_sysdig_secure_onboarding.go
sysdig/data_source_sysdig_secure_onboarding_test.go
sysdig/internal/client/v2/onboarding.go
sysdig/provider.go
website/docs/d/secure_agentless_scanning_assets.md

* add a new datasource `sysdig_secure_agentless_scanning_assets` which has information required for integrating with agentless scanning secure services.

feat(datasource): agentless scanning assets

---

sysdig/data_source_sysdig_secure_posture_policy.go
sysdig/resource_sysdig_secure_posture_policy.go

nested groups were not set as expected .
fix - set the nested group

fix | set nested groups

---

sysdig/data_source_sysdig_secure_posture_policy.go
sysdig/resource_sysdig_secure_posture_policy.go

missing groups when do import . 
fix -> add set groups

fix | posture policy missing groups 

---

sysdig/internal/client/v2/model_posture_control.go

feat(policies) support resource kind display name

---

examples/serverless-agent/fargate/orchestrator/README.md
examples/serverless-agent/fargate/orchestrator/orchestrator.tf
examples/serverless-agent/fargate/orchestrator/output.tf
examples/serverless-agent/fargate/orchestrator/providers.tf
examples/serverless-agent/fargate/orchestrator/variables.tf
examples/serverless-agent/fargate/orchestrator/versions.tf
examples/serverless-agent/fargate/workload/README.md
examples/serverless-agent/fargate/workload/instrumented_load.tf
examples/serverless-agent/fargate/workload/output.tf
examples/serverless-agent/fargate/workload/providers.tf
examples/serverless-agent/fargate/workload/variables.tf
examples/serverless-agent/fargate/workload/versions.tf

Add Serverless Agent example deployments. These will be referenced by updated public Docs.
Ref: DOC-4176

chore(docs): Add Serverless Agent examples

---

sysdig/resource_sysdig_secure_cloud_auth_account_test.go

cloudauth_account: fix oci test

---

CODEOWNERS

chore(codeowners): Tidy up owners
